### ISSUE TITLE
CIFAR-100 Mean & Standard Deviation

### ISSUE THREAD

**Issue by superctj** [wetliu/energy_ood#11]
Hi, a quick question: in https://github.com/wetliu/energy_ood/blob/77f3c09b788bb5a7bfde6fd3671228320ea0949c/CIFAR/test.py#L53, do you use the same mean and std of CIFAR-10 for CIFAR-100 experiments?

**Comment by weitliu** [comment]
Please read my README again carefully. The standard is set by OE, not by us and we only do minimal and necessary changes so that our results are reported instead of long of different changes in favor our method. If you do have questions why things are done in our code, please refer to OE first and see if you have answers there. Thanks.
