### ISSUE TITLE
Energy threshold values for OOD detection

### ISSUE THREAD

**Issue by Jinsol-Lee** [wetliu/energy_ood#8]
Hi, could you disclose the threshold values? For OOD detection, the detection accuracy values that I obtained following your description below using the in-distribution energy scores are not good. I'd appreciate any comment based on your implementation. Thank you!

> For example, if we choose FPR95, which means 95% of the in-distribution data is classified correctly, then the energy corresponded to this 95% accuracy is the threshold.
> 
> _Originally posted by @wetliu in https://github.com/wetliu/energy_ood/issues/6#issuecomment-762220795_

**Comment by weitliu** [comment]
Hello. Thanks for your interest. The threshold is not a deterministic value; it depends on how much accuracy you could endure. For example, FPR95 means you can endure 5% of the in-distribution samples are intentionally and incorrectly labeled as OOD in order to obtained a higher OOD detection score. 

Thus, your comment "detection accuracy values that I obtained following your description below using the in-distirubtion energy scores are not good" is vague to me. Are you using our in-and out-of-distribution samples or are you using your own samples? 

Perhaps the first thing first is to get figure 1 on our paper on your own. This shows the separation of in-and out-of-distribution energy score.
