### ISSUE TITLE
AUPR for All OOD Examples

### ISSUE THREAD

**Issue by superctj** [wetliu/energy_ood#9]
Thank you for open-sourcing this great work! I was running locally the experiments for CIFAR10 vs. SVHN with the method "cifar10_wrn_pretrained" and the energy score. The results (AUROC, AUPR, FPR95) are consistent with those in the paper. However, I noticed that the number of OOD examples is [set to be 1/5 of in-distribution data](https://github.com/wetliu/energy_ood/blob/f74aad3bc97820e112f287c6d6d1168842187546/CIFAR/test.py#L108), and after I ran the experiments for all OOD samples of SVHN, AUPR dropped sharply from 97.67% to 79.22%, while the other two metrics stay around the same. Are you aware of this issue, and do you have an explanation for this?

Another "problem" when running the program is that there's a warning about leaking thread. Should I be concerned about it?

**Comment by weitliu** [comment]
Thank you for your question. I do notice it is using 1/5 of the in-distribution samples, but I don't know the difference could be that big. We use the same setting as outlier-exposure, so question of this decision could be answered by them: https://github.com/hendrycks/outlier-exposure/blob/master/CIFAR/test.py#L104. 

i did notice leaking thread problem before because of this adopted code (sorry about that), and I believe it is caused by pin-memory and number of workers. Maybe you can tune those two parameters and see how it goes. It happens to me, but quite rare.

**Comment by superctj** [comment]
Thank you for the response! Could you please verify locally whether AUPR will drop if you evaluate it for all OOD samples of SVHN?

**Comment by motoight** [comment]
> Thank you for open-sourcing this great work! I was running locally the experiments for CIFAR10 vs. SVHN with the method "cifar10_wrn_pretrained" and the energy score. The results (AUROC, AUPR, FPR95) are consistent with those in the paper. However, I noticed that the number of OOD examples is [set to be 1/5 of in-distribution data](https://github.com/wetliu/energy_ood/blob/f74aad3bc97820e112f287c6d6d1168842187546/CIFAR/test.py#L108), and after I ran the experiments for all OOD samples of SVHN, AUPR dropped sharply from 97.67% to 79.22%, while the other two metrics stay around the same. Are you aware of this issue, and do you have an explanation for this?
> 
> Another "problem" when running the program is that there's a warning about leaking thread. Should I be concerned about it?

Could you please show me your test results? Cause I rerun the code with all ood samples but not found the same results。

**Comment by weitliu** [comment]
@superctj After reading some [online material](https://stats.stackexchange.com/questions/338826/auprc-vs-auc-roc), it seems to me that AUPR is for imbalanaced dataset so what you are doing is definitely harming the performance. Please confirm and see you have further questions.

**Comment by fgghhsha123** [comment]
"τ is the energy threshold. Examples with higher energies are considered as OOD inputs and
vice versa. In practice, we choose the threshold using in-distribution data so that a high fraction
of inputs are correctly classified by the OOD detector g(x)." Is the search for threshold τ implemented in the code?

**Comment by weitliu** [comment]
@fgghhsha123 No, but the threshold is not hard to read from PR and ROC curve.
